### ISSUE TITLE
Prune ratios for each step

### ISSUE THREAD

**Issue by jameslahm** [czg1225/SlimSAM#12]
Thank you for your great work! Would you mind sharing the prune ratios for each step? I don't find them in the paper or code. Thanks!

**Comment by czg1225** [comment]
Hi @jameslahm ,
For SlimSAM-50, pruning ratio is 0.5 for both step1 and step2, while for SlimSAM-77, pruning ratio is 0.77 for both step1 and step2.  You can also change the pruning ratio if you want but I suggest that the pruning ratio in step 1 and the pruning ratio in step 2 should not be too different.

**Comment by jameslahm** [comment]
Thank you!
