### ISSUE TITLE
Embedding Pruning + Bottleneck Aligning killed

### ISSUE THREAD

**Issue by ksulima** [czg1225/SlimSAM#22]
Hi,  I try to run training with default setup and one batch of SA-1B dataset which I split 50/50. The process is killed after Pruning Start:

`$ CUDA_VISIBLE_DEVICES=0 python prune_distill_step1.py  --traindata_path /home/user/SlimSAM/data/sa_1b_000000 --valdata_path /home/user/SlimSAM/data/sa_1b_000000_test --epochs 2` 

> 
CUDA AVAILABLE: True
CUDA visible devices: 1
CUDA Device Name: Tesla T4
/home/user/SlimSAM/segment_anything_kd/build_sam.py:115: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(f)
===========================Parameter Settings===========================
Pruning Ratio: 0.5
VIT num_heads: 12
norm_type: mean
imptype: Disturb
global: False
learning rate: 0.0001
a_weight: 0.5
round_to 12
TRAIN_SIZE 10000 VAL_SIZE 50 GRAD_SIZE 1000 Epochs 2
===========================Pruning Start===========================
/home/user/SlimSAM/torch_pruning/dependency.py:639: UserWarning: Unwrapped parameters detected: ['neck.1.weight', 'neck.3.weight', 'pos_embed', 'neck.1.bias', 'neck.3.bias'].
 Torch-Pruning will prune the last non-singleton dimension of a parameter. If you wish to customize this behavior, please provide an unwrapped_parameters argument.
  warnings.warn(warning_str)
Killed

Regarding the warning`weights_only` I've tried `True` and `False` and in both cases the same issue.

**Comment by czg1225** [comment]
Hi @ksulima ,
I haven't encountered this problem either, but I think it might help if you try to roll back the pytorch version.

**Comment by ksulima** [comment]
I rolled back to `python==3.8.0 pytorch==1.8.0 cuda==11.1 torchvision==0.9.0`

Now I get Cuda out of memory before Pruning Start. What was the version of python, pytorch, cuda used for training?

> Traceback (most recent call last):
  File "prune_distill_step1.py", line 302, in <module>
    train_model()
  File "prune_distill_step1.py", line 132, in train_model
    student_embedding, student_qkv_emb1, student_qkv_emb2, student_mid_emb,_= model.image_encoder(input_image)
  File "/home/user/SlimSAM/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/SlimSAM/segment_anything_kd/modeling/image_encoder.py", line 122, in forward
    x,qkv_emb,mid_emb,x_emb = blk(x)
  File "/home/user/SlimSAM/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/SlimSAM/segment_anything_kd/modeling/image_encoder.py", line 206, in forward
    x, qkv_emb = self.attn(x)
  File "/home/user/SlimSAM/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/SlimSAM/segment_anything_kd/modeling/image_encoder.py", line 292, in forward
    attn = add_decomposed_rel_pos(attn, q, self.rel_pos_h, self.rel_pos_w, (H, W), (H, W))
  File "/home/user/SlimSAM/segment_anything_kd/modeling/image_encoder.py", line 421, in add_decomposed_rel_pos
    attn.view(B, q_h, q_w, k_h, k_w) + rel_h[:, :, :, :, None] + rel_w[:, :, :, None, :]
RuntimeError: CUDA out of memory. Tried to allocate 768.00 MiB (GPU 0; 14.62 GiB total capacity; 12.57 GiB already allocated; 629.38 MiB free; 12.74 GiB reserved in total by PyTorch)

**Comment by czg1225** [comment]
@ksulima ,
I implemented Slimsam using python=3.8, pytorch=1.7, and torchvision=0.8. The GPU is a single 24gb Titan RTX GPU. I hope this can help you.
