### ISSUE TITLE
SlimSAM in transformers.js

### ISSUE THREAD

**Issue by merveenoyan** [czg1225/SlimSAM#7]
Hello 👋  wanted to ping you about recent transformers.js release. @xenova recently ported SlimSAM to run in browser and the demo can be found here in case you'd like check it out. https://huggingface.co/spaces/Xenova/segment-anything-web

**Comment by merveenoyan** [comment]
closed by #6

**Comment by czg1225** [comment]
Thanks！

**Comment by xenova** [comment]
Great 😇 @czg1225 I've resolved the conflicts with the README in the PR (https://github.com/czg1225/SlimSAM/pull/6). Please let me know if there is anything else you'd like me to add/change.
